### ISSUE TITLE
fix error

### ISSUE THREAD

**Issue by MarcinPolewski** [MarcinPolewski/Task-Manager-Project#8]
saving subdirectory causes an error:
	... 56 more
Caused by: java.lang.IllegalStateException: Multiple representations of the same entity [com.marcin.jacek.polewski.Task_Manager_Project.model.taskManager.TaskManager#1] are being merged. Detached: [com.marcin.jacek.polewski.Task_Manager_Project.model.taskManager.TaskManager@1e3cb47c]; Detached: [com.marcin.jacek.polewski.Task_Manager_Project.model.taskManager.TaskManager@74202cc5]
	at org.hibernate.event.internal.EntityCopyNotAllowedObserver.entityCopyDetected(EntityCopyNotAllowedObserver.java:45)
	at org.hibernate.event.spi.MergeContext.put(MergeContext.java:237)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:423)
	at org.hibernate.event.internal.DefaultMergeEventListener.merge(DefaultMergeEventListener.java:210)
	at org.hibernate.event.internal.DefaultMergeEventListener.doMerge(DefaultMergeEventListener.java:148)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:132)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:871)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:842)
	at org.hibernate.engine.spi.CascadingActions$6.cascade(CascadingActions.java:253)
	at org.hibernate.engine.spi.CascadingActions$6.cascade(CascadingActions.java:243)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:517)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:439)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:224)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:157)
	at org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:487)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:296)
	at org.hibernate.event.internal.DefaultMergeEventListener.merge(DefaultMergeEventListener.java:213)
	at org.hibernate.event.internal.DefaultMergeEventListener.doMerge(DefaultMergeEventListener.java:148)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:132)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:871)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:842)
	at org.hibernate.engine.spi.CascadingActions$6.cascade(CascadingActions.java:253)
	at org.hibernate.engine.spi.CascadingActions$6.cascade(CascadingActions.java:243)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:517)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:439)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:224)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:551)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:481)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:442)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:224)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:157)
	at org.hibernate.event.internal.DefaultMergeEventListener.cascadeOnMerge(DefaultMergeEventListener.java:653)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:427)
	at org.hibernate.event.internal.DefaultMergeEventListener.merge(DefaultMergeEventListener.java:210)
	at org.hibernate.event.internal.DefaultMergeEventListener.doMerge(DefaultMergeEventListener.java:148)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:132)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:86)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:850)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:836)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:319)
	at jdk.proxy2/jdk.proxy2.$Proxy99.merge(Unknown Source)
	at com.marcin.jacek.polewski.Task_Manager_Project.model.taskDirectory.TaskDirectoryDAOJPA.update(TaskDirectoryDAOJPA.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by MarcinPolewski** [comment]
does only occur when creating a sub directory of a sub directory

**Comment by MarcinPolewski** [comment]
when new sub dir is created, new task manager is loaded
